# Home Assistant - Pesukone
# (c) Kimmo Hyötynen - https://hyotynen.iki.fi

# Kustomoinnit
homeassistant:
  customize:
    switch.tplink3:
      friendly_name: Pääkytkin
      icon: mdi:power-standby

    sensor.my_tp_switch_watts:
      friendly_name: Pesukoneen ottoteho
      icon: mdi:flash

# Ajastin pesukoneen yleisimmän pesuohjelman seurantaan
timer:
  pesukone:
    duration: '01:45:00'

# TP-Link HS110, kiinni pesukoneen virtajohdossa
tplink:
  discovery: false
  switch:
    - host: !secret tplink3_host
#      name: tplink3

# Erillinen sensori TP-Linkin tehon lukemiseen
sensor:
  - platform: template
    sensors:
      my_tp_switch_watts:
        value_template: '{{ states.switch.tplink3.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'

# Automaatiot pesukonetta varten
automation:
  - alias: 'Pesukoneen ajastin käyntiin kun teho nousee'
    trigger:
      platform: numeric_state
      entity_id: sensor.my_tp_switch_watts
      above: '100'
    condition:
      condition: state
      entity_id: timer.pesukone
      state: 'idle'
    action:
      - service: timer.cancel
        entity_id: timer.pesukone
      - service: timer.start
        entity_id: timer.pesukone

  - alias: 'Viestin lähetys kun pesukone on pessyt'
    trigger:
      platform: numeric_state
      entity_id: sensor.my_tp_switch_watts
      below: '50'
    condition:
      condition: state
      entity_id: timer.pesukone
      state: 'active'
    action:
      - service: timer.stop
        entity_id: timer.pesukone
      - service: notify.email_kimmo
        data:
          message: 'Pesukone on pessyt!'

